---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: quay.io/pycontribs/python:3.8-slim-buster
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
